### ISSUE TITLE
[FR] Add support for JPEG XL

### ISSUE THREAD

**Issue by murlakatamenka** [chrontax/comiconv#1]
The reasoning is simple:

JPEG XL can **_losslessly_** reduce the size of an image in any popular image format, it's important for already lossy `.jpg`'s in existing comic books.

Sadly it's not supported in `image` crate, but [`jpegxl-sys`](https://lib.rs/crates/jpegxl-sys) exists.

**Comment by chrontax** [comment]
I can't use jpegxl-sys due to a licensing issue (comiconv is mit/apache and jpegxl is gpl), but [`zune-jpegxl`](https://crates.io/crates/zune-jpegxl) for encoding and [`jxl-oxide`](https://crates.io/crates/jxl-oxide) for decoding might work (and it would be pure rust).

**Comment by chrontax** [comment]
Check whether it works for you too.

**Comment by murlakatamenka** [comment]
Thanks!

I've checked it:

```
cargo install --git <repo_url>

# Installed package `comiconv v0.3.3 (https://github.com/chrontax/comiconv#e2a9ed36)` (executable `comiconv`)

comiconv -f jxl -q 100 comics.zip
```

The comics (130 MiB, 163 JPEG images = 134 MiB uncompressed) became 4x larger (405 MiB) and it took ~7 minutes to do the job. The progress bar shows that all 163 files are processed very fast (a few seconds), then the app "hangs" (i.e. prints no output) until it actually finishes.

Compressing all 163 images via `cjxl` takes 11 seconds:

```sh
parallel cjxl -q 100 --lossless_jpeg=1 {} {.}.jxl ::: *.jpg

# or

fd . -e jpg -x cjxl -q 100 --lossless_jpeg=1 {} {.}.jxl
```

And the final size is ~110 MiB, with lossless jpeg -> jxl conversion.

---

So, yeah, it works, but the result is definitely not what was expected.

**Comment by chrontax** [comment]
Then it must be that zune-jpegxl is quite a poor implementation. Guess I'll have to look for something else.

**Comment by chrontax** [comment]
For now I'll leave jpegxl encoding as is, as I can't seem to find a better library that would be compatible licnese-wise, and it is not of utmost priority to me.
